// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: TursomMsg.proto

package tursom_im_protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FailType int32

const (
	FailType_UNKNOWN           FailType = 0
	FailType_IN_BLACKLIST      FailType = 1 // 在对象的黑名单中
	FailType_TARGET_NOT_LOGIN  FailType = 2 // 对象未登录
	FailType_MSG_SAVE_FAILURE  FailType = 3 // 消息存储失败
	FailType_TARGET_IS_EMPTY   FailType = 4 // 目标为空
	FailType_GROUP_NOT_EXIST   FailType = 5 // 群组不存在
	FailType_GROUP_MUTED       FailType = 6 // 群组被禁言
	FailType_GROUP_USER_MUTED  FailType = 7 // 当前用户被群组禁言
	FailType_USER_NOT_IN_GROUP FailType = 8 // 当前用户不在群组中
)

// Enum value maps for FailType.
var (
	FailType_name = map[int32]string{
		0: "UNKNOWN",
		1: "IN_BLACKLIST",
		2: "TARGET_NOT_LOGIN",
		3: "MSG_SAVE_FAILURE",
		4: "TARGET_IS_EMPTY",
		5: "GROUP_NOT_EXIST",
		6: "GROUP_MUTED",
		7: "GROUP_USER_MUTED",
		8: "USER_NOT_IN_GROUP",
	}
	FailType_value = map[string]int32{
		"UNKNOWN":           0,
		"IN_BLACKLIST":      1,
		"TARGET_NOT_LOGIN":  2,
		"MSG_SAVE_FAILURE":  3,
		"TARGET_IS_EMPTY":   4,
		"GROUP_NOT_EXIST":   5,
		"GROUP_MUTED":       6,
		"GROUP_USER_MUTED":  7,
		"USER_NOT_IN_GROUP": 8,
	}
)

func (x FailType) Enum() *FailType {
	p := new(FailType)
	*p = x
	return p
}

func (x FailType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailType) Descriptor() protoreflect.EnumDescriptor {
	return file_TursomMsg_proto_enumTypes[0].Descriptor()
}

func (FailType) Type() protoreflect.EnumType {
	return &file_TursomMsg_proto_enumTypes[0]
}

func (x FailType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailType.Descriptor instead.
func (FailType) EnumDescriptor() ([]byte, []int) {
	return file_TursomMsg_proto_rawDescGZIP(), []int{0}
}

type ImMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId string `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	// Types that are assignable to Content:
	//	*ImMsg_LoginRequest
	//	*ImMsg_LoginResult
	//	*ImMsg_ChatMsg
	//	*ImMsg_SendMsgRequest
	//	*ImMsg_SendMsgResponse
	Content isImMsg_Content `protobuf_oneof:"content"`
}

func (x *ImMsg) Reset() {
	*x = ImMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TursomMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImMsg) ProtoMessage() {}

func (x *ImMsg) ProtoReflect() protoreflect.Message {
	mi := &file_TursomMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImMsg.ProtoReflect.Descriptor instead.
func (*ImMsg) Descriptor() ([]byte, []int) {
	return file_TursomMsg_proto_rawDescGZIP(), []int{0}
}

func (x *ImMsg) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (m *ImMsg) GetContent() isImMsg_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *ImMsg) GetLoginRequest() *LoginRequest {
	if x, ok := x.GetContent().(*ImMsg_LoginRequest); ok {
		return x.LoginRequest
	}
	return nil
}

func (x *ImMsg) GetLoginResult() *LoginResult {
	if x, ok := x.GetContent().(*ImMsg_LoginResult); ok {
		return x.LoginResult
	}
	return nil
}

func (x *ImMsg) GetChatMsg() *ChatMsg {
	if x, ok := x.GetContent().(*ImMsg_ChatMsg); ok {
		return x.ChatMsg
	}
	return nil
}

func (x *ImMsg) GetSendMsgRequest() *SendMsgRequest {
	if x, ok := x.GetContent().(*ImMsg_SendMsgRequest); ok {
		return x.SendMsgRequest
	}
	return nil
}

func (x *ImMsg) GetSendMsgResponse() *SendMsgResponse {
	if x, ok := x.GetContent().(*ImMsg_SendMsgResponse); ok {
		return x.SendMsgResponse
	}
	return nil
}

type isImMsg_Content interface {
	isImMsg_Content()
}

type ImMsg_LoginRequest struct {
	LoginRequest *LoginRequest `protobuf:"bytes,2,opt,name=loginRequest,proto3,oneof"`
}

type ImMsg_LoginResult struct {
	LoginResult *LoginResult `protobuf:"bytes,3,opt,name=loginResult,proto3,oneof"`
}

type ImMsg_ChatMsg struct {
	ChatMsg *ChatMsg `protobuf:"bytes,4,opt,name=chatMsg,proto3,oneof"`
}

type ImMsg_SendMsgRequest struct {
	SendMsgRequest *SendMsgRequest `protobuf:"bytes,5,opt,name=sendMsgRequest,proto3,oneof"`
}

type ImMsg_SendMsgResponse struct {
	SendMsgResponse *SendMsgResponse `protobuf:"bytes,6,opt,name=sendMsgResponse,proto3,oneof"`
}

func (*ImMsg_LoginRequest) isImMsg_Content() {}

func (*ImMsg_LoginResult) isImMsg_Content() {}

func (*ImMsg_ChatMsg) isImMsg_Content() {}

func (*ImMsg_SendMsgRequest) isImMsg_Content() {}

func (*ImMsg_SendMsgResponse) isImMsg_Content() {}

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TursomMsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TursomMsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_TursomMsg_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success  bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ImUserId string `protobuf:"bytes,2,opt,name=imUserId,proto3" json:"imUserId,omitempty"`
}

func (x *LoginResult) Reset() {
	*x = LoginResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TursomMsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResult) ProtoMessage() {}

func (x *LoginResult) ProtoReflect() protoreflect.Message {
	mi := &file_TursomMsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResult.ProtoReflect.Descriptor instead.
func (*LoginResult) Descriptor() ([]byte, []int) {
	return file_TursomMsg_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginResult) GetImUserId() string {
	if x != nil {
		return x.ImUserId
	}
	return ""
}

type MsgContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Content:
	//	*MsgContent_Msg
	Content isMsgContent_Content `protobuf_oneof:"content"`
}

func (x *MsgContent) Reset() {
	*x = MsgContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TursomMsg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgContent) ProtoMessage() {}

func (x *MsgContent) ProtoReflect() protoreflect.Message {
	mi := &file_TursomMsg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgContent.ProtoReflect.Descriptor instead.
func (*MsgContent) Descriptor() ([]byte, []int) {
	return file_TursomMsg_proto_rawDescGZIP(), []int{3}
}

func (m *MsgContent) GetContent() isMsgContent_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *MsgContent) GetMsg() string {
	if x, ok := x.GetContent().(*MsgContent_Msg); ok {
		return x.Msg
	}
	return ""
}

type isMsgContent_Content interface {
	isMsgContent_Content()
}

type MsgContent_Msg struct {
	Msg string `protobuf:"bytes,1,opt,name=msg,proto3,oneof"`
}

func (*MsgContent_Msg) isMsgContent_Content() {}

type SendMsgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Receiver string      `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	ReqId    string      `protobuf:"bytes,2,opt,name=reqId,proto3" json:"reqId,omitempty"`
	Content  *MsgContent `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *SendMsgRequest) Reset() {
	*x = SendMsgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TursomMsg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgRequest) ProtoMessage() {}

func (x *SendMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TursomMsg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgRequest.ProtoReflect.Descriptor instead.
func (*SendMsgRequest) Descriptor() ([]byte, []int) {
	return file_TursomMsg_proto_rawDescGZIP(), []int{4}
}

func (x *SendMsgRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *SendMsgRequest) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

func (x *SendMsgRequest) GetContent() *MsgContent {
	if x != nil {
		return x.Content
	}
	return nil
}

type SendMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Receiver string   `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	ReqId    string   `protobuf:"bytes,2,opt,name=reqId,proto3" json:"reqId,omitempty"`
	Success  bool     `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	FailMsg  string   `protobuf:"bytes,4,opt,name=failMsg,proto3" json:"failMsg,omitempty"`
	FailType FailType `protobuf:"varint,5,opt,name=failType,proto3,enum=FailType" json:"failType,omitempty"`
}

func (x *SendMsgResponse) Reset() {
	*x = SendMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TursomMsg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgResponse) ProtoMessage() {}

func (x *SendMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TursomMsg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgResponse.ProtoReflect.Descriptor instead.
func (*SendMsgResponse) Descriptor() ([]byte, []int) {
	return file_TursomMsg_proto_rawDescGZIP(), []int{5}
}

func (x *SendMsgResponse) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *SendMsgResponse) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

func (x *SendMsgResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendMsgResponse) GetFailMsg() string {
	if x != nil {
		return x.FailMsg
	}
	return ""
}

func (x *SendMsgResponse) GetFailType() FailType {
	if x != nil {
		return x.FailType
	}
	return FailType_UNKNOWN
}

type ChatMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Receiver string      `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Sender   string      `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Content  *MsgContent `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *ChatMsg) Reset() {
	*x = ChatMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TursomMsg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsg) ProtoMessage() {}

func (x *ChatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_TursomMsg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsg.ProtoReflect.Descriptor instead.
func (*ChatMsg) Descriptor() ([]byte, []int) {
	return file_TursomMsg_proto_rawDescGZIP(), []int{6}
}

func (x *ChatMsg) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *ChatMsg) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ChatMsg) GetContent() *MsgContent {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_TursomMsg_proto protoreflect.FileDescriptor

var file_TursomMsg_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x54, 0x75, 0x72, 0x73, 0x6f, 0x6d, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xae, 0x02, 0x0a, 0x05, 0x49, 0x6d, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6d,
	0x73, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49,
	0x64, 0x12, 0x33, 0x0a, 0x0c, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x24, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74,
	0x4d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x43, 0x68, 0x61, 0x74,
	0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x07, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x39,
	0x0a, 0x0e, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0e, 0x73, 0x65, 0x6e, 0x64, 0x4d,
	0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x0f, 0x73, 0x65, 0x6e,
	0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0f, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x22, 0x24, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x43, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2b, 0x0a,
	0x0a, 0x4d, 0x73, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x42,
	0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x69, 0x0a, 0x0e, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x71, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x71, 0x49, 0x64, 0x12, 0x25,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x4d, 0x73, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x9e, 0x01, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x71, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x71, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x61, 0x69, 0x6c, 0x4d, 0x73, 0x67,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x61, 0x69, 0x6c, 0x4d, 0x73, 0x67, 0x12,
	0x25, 0x0a, 0x08, 0x66, 0x61, 0x69, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x09, 0x2e, 0x46, 0x61, 0x69, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x66, 0x61,
	0x69, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x22, 0x64, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x73,
	0x67, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4d, 0x73, 0x67, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2a, 0xbd, 0x01, 0x0a,
	0x08, 0x46, 0x61, 0x69, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x4e, 0x5f, 0x42, 0x4c, 0x41,
	0x43, 0x4b, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x41, 0x52, 0x47,
	0x45, 0x54, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x02, 0x12, 0x14,
	0x0a, 0x10, 0x4d, 0x53, 0x47, 0x5f, 0x53, 0x41, 0x56, 0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x55,
	0x52, 0x45, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x54, 0x41, 0x52, 0x47, 0x45, 0x54, 0x5f, 0x49,
	0x53, 0x5f, 0x45, 0x4d, 0x50, 0x54, 0x59, 0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f, 0x47, 0x52, 0x4f,
	0x55, 0x50, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10, 0x05, 0x12, 0x0f,
	0x0a, 0x0b, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x4d, 0x55, 0x54, 0x45, 0x44, 0x10, 0x06, 0x12,
	0x14, 0x0a, 0x10, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4d, 0x55,
	0x54, 0x45, 0x44, 0x10, 0x07, 0x12, 0x15, 0x0a, 0x11, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4e, 0x4f,
	0x54, 0x5f, 0x49, 0x4e, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x10, 0x08, 0x42, 0x18, 0x48, 0x01,
	0x5a, 0x14, 0x2e, 0x2f, 0x74, 0x75, 0x72, 0x73, 0x6f, 0x6d, 0x5f, 0x69, 0x6d, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_TursomMsg_proto_rawDescOnce sync.Once
	file_TursomMsg_proto_rawDescData = file_TursomMsg_proto_rawDesc
)

func file_TursomMsg_proto_rawDescGZIP() []byte {
	file_TursomMsg_proto_rawDescOnce.Do(func() {
		file_TursomMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_TursomMsg_proto_rawDescData)
	})
	return file_TursomMsg_proto_rawDescData
}

var file_TursomMsg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_TursomMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_TursomMsg_proto_goTypes = []interface{}{
	(FailType)(0),           // 0: FailType
	(*ImMsg)(nil),           // 1: ImMsg
	(*LoginRequest)(nil),    // 2: LoginRequest
	(*LoginResult)(nil),     // 3: LoginResult
	(*MsgContent)(nil),      // 4: MsgContent
	(*SendMsgRequest)(nil),  // 5: SendMsgRequest
	(*SendMsgResponse)(nil), // 6: SendMsgResponse
	(*ChatMsg)(nil),         // 7: ChatMsg
}
var file_TursomMsg_proto_depIdxs = []int32{
	2, // 0: ImMsg.loginRequest:type_name -> LoginRequest
	3, // 1: ImMsg.loginResult:type_name -> LoginResult
	7, // 2: ImMsg.chatMsg:type_name -> ChatMsg
	5, // 3: ImMsg.sendMsgRequest:type_name -> SendMsgRequest
	6, // 4: ImMsg.sendMsgResponse:type_name -> SendMsgResponse
	4, // 5: SendMsgRequest.content:type_name -> MsgContent
	0, // 6: SendMsgResponse.failType:type_name -> FailType
	4, // 7: ChatMsg.content:type_name -> MsgContent
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_TursomMsg_proto_init() }
func file_TursomMsg_proto_init() {
	if File_TursomMsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_TursomMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TursomMsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TursomMsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TursomMsg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TursomMsg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMsgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TursomMsg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TursomMsg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_TursomMsg_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ImMsg_LoginRequest)(nil),
		(*ImMsg_LoginResult)(nil),
		(*ImMsg_ChatMsg)(nil),
		(*ImMsg_SendMsgRequest)(nil),
		(*ImMsg_SendMsgResponse)(nil),
	}
	file_TursomMsg_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*MsgContent_Msg)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TursomMsg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TursomMsg_proto_goTypes,
		DependencyIndexes: file_TursomMsg_proto_depIdxs,
		EnumInfos:         file_TursomMsg_proto_enumTypes,
		MessageInfos:      file_TursomMsg_proto_msgTypes,
	}.Build()
	File_TursomMsg_proto = out.File
	file_TursomMsg_proto_rawDesc = nil
	file_TursomMsg_proto_goTypes = nil
	file_TursomMsg_proto_depIdxs = nil
}
